title: Kelly Heard
logo: /assets/img/notioned-kelly-sm.png
description: > 
I’m a Product Manager for a SaaS product and future serial micro-SaaS entrepreneur. 

Notes and other links found here
theme: jekyll-theme-minimal
exclude: README.md
